name: Deploy Backend Stage

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # STEP 1: FILE TRANSFER (FTP)
      # This handles exclusions so you don't upload massive folders.
      - name: Deploy files to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER_LIVE }}
          username: ${{ secrets.FTP_USERNAME_LIVE }}
          password: ${{ secrets.FTP_PASSWORD_LIVE }}
          port: 21
          protocol: ftp
          local-dir: ./
          server-dir: /backendhandler/
          dangerous-clean-remote: false
          exclude: |
            **/.git*/**
            **/.github/**
            **/node_modules/**
            **/.env*
            **/images/**
            **/public/images/**
            **/storage/*.key
            **/storage/app/**
            **/storage/framework/**
            **/storage/logs/**
            **/bootstrap/cache/**
            **/vendor/**

      